# define url to load current list of companies on exchange, filtered by volume and price, and limited number of days to load

development:
# for now using Australian securities exchange (ASX)
  :asx_list_url: 'http://www.asx.com.au/asx/research/ASXListedCompanies.csv'
  :filter_volume: 50000
  :filter_price: 0.2
  :max_days: 800
  :exchange_name: 'ASX'